.key now gets generated

diff --git a/noted b/noted
--- a/noted
+++ b/noted
@@ -1,6 +1,42 @@
 #!/bin/bash
+RED='\033[0;31m'
+YELLOW='\033[1;33m'
+GREEN='\033[92m'
+NC='\033[0m'
+# Helper Functions
+error () {
+	printf "[${RED}ERROR${NC}] $1\n"
+	exit $2
+}
+
+warning () {
+	printf "[${YELLOW}WARNING${NC}] $1\n"
+}
+
+success () {
+	printf "[${GREEN}SUCCESS${NC}] $1\n"
+}
+
+tick () {
+	printf "$1 ${GREEN}✔${NC}\n"
+}
+
+# Begin
 workdir="$HOME/Documents/noted"
-mkdir $workdir
+if [ ! -d $workdir ]
+then
+	mkdir $workdir
+fi
+
+if [ ! -f "$workdir/.key" ]
+then
+	cat << EOF > "$workdir/.key"
+nic:<your nickname>
+key:<your key generated by folder>
+EOF
+	error ".key file missing, generating \'$workdir/.key\'... Please fill it out."
+fi
+
 height=$(ls -1 $workdir | wc -l)
 height=$(echo $height + 1 | bc)
 file=$(echo -e "NEW\n$(ls -1 $workdir)" | dmenu -l "$height" -p "Files:")
