WIP: Refactor and tty mode
Good progress, refactor is working (so far what i have tested that is)
and work has started in tty mode. currently working on getting a list of
files.

diff --git a/noted b/noted
--- a/noted
+++ b/noted
@@ -1,5 +1,6 @@
 #!/bin/bash
 # Defaults
+version="1.1"
 workdir="$HOME/Documents/noted"
 
 ### Start Helper Functions ###
@@ -7,6 +8,19 @@ RED='\033[0;31m'
 YELLOW='\033[1;33m'
 GREEN='\033[92m'
 NC='\033[0m'
+usage () {
+	cat << EOF
+noted - Simple note keeping $version
+
+Usage: noted [options]
+
+Arguments:
+	-h: Shows this message.
+	-v: Enable verbose printing.
+	-t: Force tty mode (WIP).
+EOF
+	exit $1
+}
 error () {
 	printf "[${RED}ERROR${NC}] $1\n"
 	exit $2
@@ -28,17 +42,19 @@ sq () {
 	echo $(sed -e 's/^"//' -e 's/"$//' <<< $1)
 }
 
+# Check that a dependency is met
+# usage: assert_package ls
 assert_package () {
 	[ ! $(command -v "$1") ] && error "Missing Package \'$1\'."
 }
 
 # Upload a file
 upload () {
-	echo "[UPLOADING] $1"
+	verbose "[UPLOADING] $1"
 	route="$domain/upload/note"
 	content=$(cat $1)
 	fname=$(basename $1)
-	curl -s -X POST -F "nic=$nic" -F "key=$privkey" -F "fname=$fname" -F "content=$content" $route
+	curl -s -X POST -F "nic=$nic" -F "key=$privkey" -F "fname=$fname" -F "content=$content" $route > /dev/null
 }
 
 # Download a file
@@ -68,89 +84,174 @@ sync () {
 		echo "Sync for <$1> failed."
 	fi
 }
+
+# determine what file/note we will be writing/ syncing to.
+# Results:
+# file=NEW -> we create a new file.
+# file=SYNC -> Sync all files.
+# file=<filename>
+setfile () {
+	height=$(ls -1 $workdir | wc -l)
+	height=$(echo $height + 1 | bc)
+	file=$(echo -e "NEW\nSYNC\nEXIT\n$(ls -1 $workdir)" | dmenu -l "$height" -p "Files:")
+	if [ $? -eq 1 ]
+	then
+		exit 0 # User exited dmenu
+	fi
+}
+
+# Prep file, and set $file var
+# Usage: open "some_file"
+open () {
+	sync $1 # Sync the file we want to write too.
+	file="$workdir/$1"
+	touch "$file"
+}
+
+# Prints message if verbose is set
+verbose () {
+	if [ ! -z $verbose ]
+	then
+		echo "$1"
+	fi
+}
 ### End Helper Functions ###
 
-# Check dependencies
-assert_package dmenu
-assert_package jq
+# Init function, generates config templates, and checks dependencies
+init () {
+	# Check dependencies
+	assert_package dmenu
+	assert_package jq
 
-# Begin
-if [ ! -d $workdir ]
-then
-	mkdir $workdir
-fi
+	# Begin
+	if [ ! -d $workdir ]
+	then
+		mkdir $workdir
+	fi
 
-if [ ! -f "$workdir/.key" ]
-then
-	cat << EOF > "$workdir/.key"
+	if [ ! -f "$workdir/.key" ]
+	then
+		cat << EOF > "$workdir/.key"
 nic=<your_nickname>
 key=<your_key>
 domain=http://localhost:5000
+editor=vim
 EOF
-	error ".key file missing, generating \'$workdir/.key\'... Please fill it out."
-fi
-
-while IFS== read -r key val
-do
-	if [ $key = 'key' ]
-	then
-		privkey=$val
-	elif [ $key = 'nic' ]
-	then
-		nic=$val
-	else
-		domain=$val
+		error ".key file missing, generating \'$workdir/.key\'... Please fill it out."
 	fi
-done < "$workdir/.key"
 
-height=$(ls -1 $workdir | wc -l)
-height=$(echo $height + 1 | bc)
-file=$(echo -e "NEW\nSYNC\n$(ls -1 $workdir)" | dmenu -l "$height" -p "Files:")
-if [ $? -eq 1 ]
-then
-	exit 0
-fi
-
-if [ $file = "NEW" ]
-then
-	file=$(echo "" | dmenu -p "Enter Filename:")
-elif [ "$file" = "SYNC" ]
-then
-	# Sync everything.
-	for f in $workdir/*
+	while IFS== read -r key val
 	do
-		sync "$f"
-	done
-	exit 0
-fi
+		if [ $key = 'key' ]
+		then
+			privkey=$val
+		elif [ $key = 'nic' ]
+		then
+			nic=$val
+		elif [ $key = 'domain' ]
+		then
+			domain=$val
+		elif [ $key = 'editor' ]
+		then
+			editor=$val
+		fi
+	done < "$workdir/.key"
+}
 
-if [ $? -eq 1 ]
-then
-	exit 0
-fi
+# This spawns a gui that allows interacting with noted.
+gui () {
+	setfile
+	if [ $file = "NEW" ]
+	then
+		file=$(echo "" | dmenu -p "Enter Filename:")
+	elif [ "$file" = "SYNC" ]
+	then
+		# Sync everything.
+		for f in $workdir/*
+		do
+			sync "$f"
+		done
+		return 0
+	elif [ "$file" = "EXIT" ]
+	then
+		exit 0
+	fi
 
-sync $file # Sync the file we want to write too.
-file="$workdir/$file"
-touch "$file"
+	if [ $? -eq 1 ]
+	then
+		return 0
+	fi
 
-height=$(wc -l "$file" | awk '{print $1}')
-prompt="Add/delete a task: "
+	open $file
 
-# Loop Credit too https://tools.suckless.org/dmenu/scripts/todo
-cmd=$(dmenu -l "$height" -p "$prompt" "$@" < "$file")
-while [ -n "$cmd" ]; do
- 	if grep -q "^$cmd\$" "$file"; then
-		grep -v "^$cmd\$" "$file" > "$file.$$"
-		mv "$file.$$" "$file"
-        height=$(( height - 1 ))
- 	else
-		echo "$cmd" >> "$file"
-		height=$(( height + 1 ))
- 	fi
+	height=$(wc -l "$file" | awk '{print $1}')
+	prompt="Add/delete a task: "
 
+	# Loop Credit too https://tools.suckless.org/dmenu/scripts/todo
 	cmd=$(dmenu -l "$height" -p "$prompt" "$@" < "$file")
-done
-### End Suckless
+	while [ -n "$cmd" ]; do
+		if grep -q "^$cmd\$" "$file"; then
+			grep -v "^$cmd\$" "$file" > "$file.$$"
+			mv "$file.$$" "$file"
+			height=$(( height - 1 ))
+		else
+			echo "$cmd" >> "$file"
+			height=$(( height + 1 ))
+		fi
 
-# Update
-upload $file
+		cmd=$(dmenu -l "$height" -p "$prompt" "$@" < "$file")
+	done
+	### End Suckless
+
+	# Update
+	upload $file
+}
+
+cli () {
+	clear
+	echo TODO: TTY Mode.
+
+	IFS=', '
+	i=1
+	files=()
+	read -a files <<< "$(ls -m $workdir)"
+	for file in ${files[@]}
+	do
+		echo "$i. $file"
+		i=$(( i + 1 ))
+	done
+	exit 0 # This is just temporary
+}
+
+main () {
+	while getopts "hvt" opt
+	do
+		case $opt in
+			h)
+				usage 0
+				;;
+			v)
+				verbose=1
+				;;
+			t)
+				istty=0
+				;;
+			*)
+				error "Invalid arg" 1
+				;;
+		esac
+	done
+	init
+
+	for ((;;))
+	do
+		if [ -z $istty ]
+		then
+			gui
+		else
+			cli
+		fi
+	done
+}
+
+main "$@"
